# Generated by Django 4.2.2 on 2023-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruskinvetapp', '0002_record_delete_communications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
